default:
    csrf: true,
    recaptcha: [
        enabled: false
        label: "Please enter the CAPTCHA text to prove you're a human"
        public_key: ''
        private_key: ''
        error_message: "The CAPTCHA wasn't entered correctly. Please try again."
        theme: 'clean'
        badge_location': 'bottomright'
    ]
    templates: [
        ajax: '@BoltForms/asset/_ajax.twig'
        css: '@BoltForms/asset/_css.twig'
        js: '@BoltForms/asset/_js.twig'
        email: '@BoltForms/email/email.twig'
        subject: '@BoltForms/email/subject.twig'
        messages: '@BoltForms/feedback/_messages.twig'
        exception: '@BoltForms/feedback/_exception.twig'
        files: '@BoltForms/file/browser.twig'
        form: '@BoltForms/form/form.twig'
        form_theme: '@BoltForms/form/_form_theme.twig'
        fields: '@BoltForms/form/_fields.twig'
        recaptcha: '@BoltForms/form/_recaptcha.twig'
        macros: '@BoltForms/_macros.twig'
    ]
    debug: [
        enabled: fals
        address: ''
    ]
    uploads: [
        enabled: false
        base_directory: '/tmp/'
        filename_handling: 'suffix'
        management_controller: false
        base_uri: 'boltforms'
    ]
    fieldmap: []
